#!/bin/sh
gofiles=$(git diff --cached --name-only --diff-filter=ACM | grep '.go$')
[ -z "$gofiles" ] && exit 0

unformatted=$(gofmt -l $gofiles)
[ -z "$unformatted" ] && exit 0

echo "Go files must be formatted with gofmt."
for fn in $unformatted; do
    echo "  gofmt -w $PWD/$fn"
    gofmt -w "$PWD/$fn"
    git add "$PWD/$fn"
done

exit 0
