server:
  host: ":8889"
  public_directory: "files/etc/voucher/public"
  template_directory: "files/etc/voucher/templates"

database:
  endpoint: "postgres://postgres:postgres@127.0.0.1:5432/EVoucher2?sslmode=disable"
