server:
  host: ":8889"
  public_directory: "files/etc/voucher/public"
  template_directory: "files/etc/voucher/templates"

database:
    endpoint: "postgres://elys:elys@127.0.0.1:5432/evoucher?sslmode=disable"
    redis: "127.0.0.1:6379"
