server:
  host: ":8889"
  public_directory: "files/etc/voucher/public"
  template_directory: "files/etc/voucher/templates"

database:
<<<<<<< HEAD
    endpoint: "postgres://elys:elys@127.0.0.1:5432/EVoucher2?sslmode=disable"
=======
  endpoint: "postgres://elys:elys@127.0.0.1:5432/evoucher2?sslmode=disable"
>>>>>>> 590afbcff7d7106e2f86adc3e8a6d4bc063de435
