server:
  host: ":8889"
  public_directory: "files/etc/voucher/public"
  template_directory: "files/etc/voucher/templates"

database:
    endpoint: "postgres://evoucher:IuA0Ayj8F0p6Iuwg@35.185.131.77:5432/evoucher?sslmode=disable"
    redis: "127.0.0.1:6379"
