server:
  host: ":8889"
  public_directory: "files/etc/voucher/public"
  template_directory: "files/etc/voucher/templates"

database:
#    endpoint: "postgres://evoucher:IuA0Ayj8F0p6Iuwg@35.185.131.77:5432/evoucher?sslmode=disable"
    endpoint: "postgres://evoucher:IuA0Ayj8F0p6Iuwg@127.0.0.1:5432/evoucher?sslmode=disable"
    redis: "127.0.0.1:6379"

mailgun:
  domain: "sedayuone.com"
  mailgun_key: "key-7uktwep6lt-ma6emewjgcwx8bjjkrke8"
  mailgun_public_key: "pubkey-2slaf2guxlloalnpb3qtkruac9beajd9"
  root_mail_template: "files/etc/voucher/public/assets/mail/"

logger:
  path: "/var/log/"
  filename: "logger-evoucher"

gcs:
  bucket: "e-voucher"
  project_id: "shared-project-159515"
  public_url: "https://storage.googleapis.com/%s/%s"

ocra:
  endpoint: "http://ocra-staging.elys.id"
  apps_key: "uuvdqHUa5VHXOGxrMHYvym1OUBETZwT4r2S7YfxmQOSL9dgIhxJAH8vTrNNVwGxi"

voucher:
  link: "voucher.elys.id/public/redeem"
